"use strict";
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const state={scenarios:[],agents:[],skills:[],incidents:[],current:null,selectedEventId:null,auditValid:null,running:false,resumeAfterApproval:false};
const statusLabels={detected:"已接入",triaging:"采集证据",diagnosing:"根因诊断",planning:"生成方案",awaiting_approval:"等待审批",executing:"受控执行",verifying:"独立验证",rolling_back:"正在回滚",resolved:"已恢复",rolled_back:"已回滚",rejected:"已驳回"};
const terminalStatuses=new Set(["resolved","rolled_back","rejected"]);
const pipelineOrder=["detected","triaging","diagnosing","planning","awaiting_approval","executing","verifying","resolved"];
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined&&text!==null)node.textContent=String(text);return node}
function announce(message){$("#announcer").textContent=message}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const payload=await response.json();if(!response.ok){const error=new Error(payload.error?.message||`HTTP ${response.status}`);error.code=payload.error?.code;error.status=response.status;throw error}return payload}
async function bootstrap(){setConnection("connecting","正在连接");try{const[scenarioData,agentData,skillData]=await Promise.all([api("/api/scenarios"),api("/api/agents"),api("/api/skills")]);state.scenarios=scenarioData.items;state.agents=agentData.items;state.skills=skillData.items;renderScenarioOptions();renderAgents();bindEvents();await refreshAll();setConnection("online","本地在线")}catch(error){setConnection("offline","连接失败");announce(`初始化失败：${error.message}`);setRunState(`ERROR / ${error.message}`)}}
function setConnection(connectionState,label){const pill=$("#connection-state");pill.dataset.state=connectionState;$(".connection-label",pill).textContent=label}
function bindEvents(){$("[data-action='create-incident']").addEventListener("click",createIncident);$("[data-action='refresh']").addEventListener("click",()=>void refreshAll().catch(reportError));$("[data-action='advance']").addEventListener("click",advanceOnce);$("[data-action='run-demo']").addEventListener("click",runDemo);$("#scenario-select").addEventListener("change",renderScenarioDetail);$("#approval-form").addEventListener("submit",approveIncident);$("[data-action='reject']").addEventListener("click",rejectIncident);const actor=$("#approval-actor");actor.addEventListener("invalid",()=>setApprovalError("请填写审批人。"));actor.addEventListener("input",()=>setApprovalError(""))}
function renderScenarioOptions(){const select=$("#scenario-select");const options=state.scenarios.map(scenario=>{const option=el("option","",`${scenario.severity} · ${scenario.name}`);option.value=scenario.id;return option});select.replaceChildren(...options);renderScenarioDetail()}
function renderScenarioDetail(){const scenario=selectedScenario();$("#scenario-detail").textContent=scenario?`${scenario.service} / ${scenario.summary} 预期：${scenario.verification_outcome==="pass"?"恢复闭环":"验证失败并回滚"}`:"没有可用故障样本。"}
function selectedScenario(){const id=$("#scenario-select").value;return state.scenarios.find(scenario=>scenario.id===id)}
function renderAgents(){const list=$("#agent-list");const activeAgent=state.current?.events.at(-1)?.agent_id;const items=state.agents.map(agent=>{const item=el("li","agent-item");item.style.setProperty("--agent-color",agent.color);item.dataset.active=String(agent.id===activeAgent);item.append(el("strong","",agent.name),el("span","",agent.role));return item});list.replaceChildren(...items)}
async function refreshAll(){const[incidentData,metrics]=await Promise.all([api("/api/incidents"),api("/api/metrics")]);state.incidents=incidentData.items;if(state.current){const updated=state.incidents.find(item=>item.id===state.current.id);state.current=updated||state.incidents[0]||null}else state.current=state.incidents[0]||null;state.auditValid=null;if(state.current){const audit=await api(`/api/incidents/${state.current.id}/audit`);state.auditValid=Boolean(audit.valid)}renderMetrics(metrics);renderIncidentList();renderCurrentIncident()}
function renderMetrics(metrics){$("#metric-total").textContent=pad(metrics.incidents_total);$("#metric-active").textContent=pad(metrics.active_total);$("#metric-resolved").textContent=pad(metrics.resolved_total);$("#metric-rollback").textContent=pad(metrics.rolled_back_total);$("#metric-audit").textContent=`${Number(metrics.audit_integrity_percent).toFixed(1)}%`;$("#metric-trace").textContent=`${Number(metrics.trace_coverage_percent).toFixed(1)}%`}
function pad(value){return String(value??0).padStart(2,"0")}
function renderIncidentList(){const list=$("#incident-list");if(!state.incidents.length){list.replaceChildren(el("p","fine-print","队列为空。创建第一个故障事件。"));return}const cards=state.incidents.map(incident=>{const button=el("button","incident-card");button.type="button";const active=state.current?.id===incident.id;button.dataset.active=String(active);button.setAttribute("aria-pressed",String(active));button.append(el("strong","",incident.scenario_name),el("span","",`${incident.severity} / ${statusLabels[incident.status]||incident.status} / ${incident.id}`));button.addEventListener("click",()=>void selectIncident(incident.id));return button});list.replaceChildren(...cards)}
async function selectIncident(id){state.current=state.incidents.find(incident=>incident.id===id)||null;state.selectedEventId=state.current?.events.at(-1)?.id||null;state.auditValid=null;renderIncidentList();renderCurrentIncident();if(!state.current)return;const incidentId=state.current.id;try{const audit=await api(`/api/incidents/${incidentId}/audit`);if(state.current?.id!==incidentId)return;state.auditValid=Boolean(audit.valid)}catch(error){if(state.current?.id===incidentId)reportError(error)}renderCurrentIncident()}
async function createIncident(){if(state.running)return;const scenario=selectedScenario();if(!scenario)return;setRunState("CREATING INCIDENT");try{const payload=await api("/api/incidents",{method:"POST",body:JSON.stringify({scenario_id:scenario.id})});state.current=payload.incident;state.selectedEventId=payload.incident.events.at(-1)?.id||null;announce(`已创建事件：${payload.incident.scenario_name}`);await refreshAll()}catch(error){reportError(error)}}
function renderCurrentIncident(){const incident=state.current;const runButton=$("[data-action='run-demo']");const stepButton=$("[data-action='advance']");const createButton=$("[data-action='create-incident']");createButton.disabled=state.running;if(!incident){runButton.disabled=true;stepButton.disabled=true;renderAgents();return}$("#incident-kicker").textContent=`${incident.id} / ${incident.service}`;$("#incident-title").textContent=incident.scenario_name;$("#incident-summary").textContent=incident.summary;$("#incident-severity").textContent=incident.severity;const status=$("#incident-status");status.textContent=statusLabels[incident.status]||incident.status;status.dataset.status=incident.status;$("#trace-id").textContent=`TRACE / ${shortHash(incident.trace_id,18)}`;const isTerminal=terminalStatuses.has(incident.status);runButton.disabled=state.running||isTerminal;stepButton.disabled=state.running||isTerminal||incident.status==="awaiting_approval";setRunState(state.running?"AUTONOMOUS LOOP ACTIVE":isTerminal?`TERMINAL / ${incident.status.toUpperCase()}`:`READY / ${incident.status.toUpperCase()}`);renderPipeline(incident);renderTimeline(incident);renderAudit(incident);renderAgents()}
function renderPipeline(incident){let currentIndex=pipelineOrder.indexOf(incident.status);const failedRollback=["rolling_back","rolled_back"].includes(incident.status);if(incident.status==="rolled_back")currentIndex=pipelineOrder.indexOf("verifying");if(incident.status==="rejected")currentIndex=pipelineOrder.indexOf("awaiting_approval");$$("#state-pipeline li").forEach((item,index)=>{const current=index===currentIndex;item.dataset.complete=String(index<currentIndex);item.dataset.current=String(current);item.dataset.error=String(failedRollback&&item.dataset.stage==="verifying");if(current)item.setAttribute("aria-current","step");else item.removeAttribute("aria-current")})}
function renderTimeline(incident){const timeline=$("#timeline");if(!incident.events.length)return;if(!state.selectedEventId)state.selectedEventId=incident.events.at(-1)?.id;const nodes=incident.events.map(event=>{const wrapper=el("article","timeline-event");const agent=state.agents.find(item=>item.id===event.agent_id);wrapper.style.setProperty("--event-color",agent?.color||"var(--acid)");const button=el("button","event-button");button.type="button";const selected=event.id===state.selectedEventId;button.dataset.selected=String(selected);button.setAttribute("aria-pressed",String(selected));button.setAttribute("aria-controls","event-detail");const meta=el("div","event-meta");meta.append(el("strong","",agent?.name||event.agent_id),el("span","",`${formatTime(event.timestamp)} / ${event.skill_id}`));const outcome=el("span","event-outcome",event.outcome);outcome.dataset.outcome=event.outcome;button.append(meta,el("span","event-summary",event.summary),outcome);button.addEventListener("click",()=>{state.selectedEventId=event.id;renderTimeline(incident);renderEventDetail(event)});wrapper.append(button);return wrapper});timeline.replaceChildren(...nodes);const selected=incident.events.find(event=>event.id===state.selectedEventId)||incident.events.at(-1);renderEventDetail(selected)}
function renderAudit(incident){const seal=$("#audit-seal");const valid=state.auditValid;seal.dataset.valid=valid===null?"unknown":String(valid);$("strong",seal).textContent=valid===null?"正在重算哈希链":valid?"哈希链完整":"哈希链异常";$("#audit-events").textContent=String(incident.events.length);$("#audit-approval").textContent=incident.approval?`${incident.approval.decision} / ${incident.approval.actor}`:"未触发";$("#audit-risk").textContent=String(incident.context.risk_score??"—")}
function renderEventDetail(event){const container=$("#event-detail");if(!event){container.replaceChildren(el("p","fine-print","暂无事件证据。"));return}const header=el("div","detail-head");header.append(el("strong","",event.action),el("span","",`SEQ ${String(event.sequence).padStart(2,"0")}`));const children=[header];if(event.evidence.length){event.evidence.forEach(item=>{const block=el("article","evidence-item");block.append(el("strong","",`${item.source} · ${item.kind}`),el("span","",item.summary));children.push(block)})}else children.push(el("p","fine-print","该事件不含外部证据，仅记录控制面动作。"));children.push(el("div","hash-line",`HASH ${event.event_hash}`));container.replaceChildren(...children);renderSkillDetail(event.skill_id)}
function renderSkillDetail(skillId){const skill=state.skills.find(item=>item.id===skillId);const container=$("#skill-detail");if(!skill){container.replaceChildren(el("span","mono-tag",skillId||"NO SKILL"));return}const tag=el("span","mono-tag",`${skill.id} / V${skill.version}`);const title=el("h3","",skill.name);const purpose=el("p","",skill.purpose);const io=contractRow("输入 → 输出",`${skill.inputs.join(", ")} → ${skill.outputs.join(", ")}`);const boundary=contractRow("安全边界",skill.security_boundary);const failure=contractRow("失败处理",skill.failure_handling);container.replaceChildren(tag,title,purpose,io,boundary,failure)}
function contractRow(label,value){const row=el("div","contract-row");row.append(el("span","",label),el("p","",value));return row}
async function advanceOnce(){if(!state.current||terminalStatuses.has(state.current.status))return;if(state.current.status==="awaiting_approval"){openApprovalDialog();return}try{const payload=await api(`/api/incidents/${state.current.id}/advance`,{method:"POST",body:"{}"});state.current=payload.incident;state.selectedEventId=state.current.events.at(-1)?.id||null;await refreshAll();if(state.current.status==="awaiting_approval")openApprovalDialog()}catch(error){if(error.code==="approval_required")openApprovalDialog();else reportError(error)}}
async function runDemo(resumeOnGate=true){if(!state.current||state.running)return;const incidentId=state.current.id;state.running=true;if(resumeOnGate)state.resumeAfterApproval=true;renderCurrentIncident();try{while(state.current&&state.current.id===incidentId&&!terminalStatuses.has(state.current.status)){if(state.current.status==="awaiting_approval"){state.running=false;renderCurrentIncident();openApprovalDialog();return}await advanceOnce();if(state.current?.id===incidentId&&terminalStatuses.has(state.current.status))break;await delay(720)}}finally{state.running=false;if(state.current?.id===incidentId&&terminalStatuses.has(state.current.status))state.resumeAfterApproval=false;renderCurrentIncident()}}
function openApprovalDialog(){const dialog=$("#approval-dialog");setApprovalError("");if(!dialog.open)dialog.showModal();$("#approval-actor").focus();setRunState("HUMAN APPROVAL REQUIRED");announce("流程暂停，等待人工审批。")}
async function approveIncident(event){event.preventDefault();if(!state.current)return;setApprovalError("");const actor=$("#approval-actor").value.trim();const reason=$("#approval-reason").value.trim();try{const payload=await api(`/api/incidents/${state.current.id}/approve`,{method:"POST",body:JSON.stringify({actor,reason})});state.current=payload.incident;state.selectedEventId=state.current.events.at(-1)?.id||null;$("#approval-dialog").close();announce(`审批人${actor}已批准执行。`);await refreshAll();if(state.resumeAfterApproval){state.resumeAfterApproval=false;await runDemo(false)}}catch(error){reportError(error,true)}}
async function rejectIncident(){if(!state.current)return;const form=$("#approval-form");if(!form.reportValidity()){setApprovalError("请填写审批人。");announce("审批表单有误：请填写审批人。");return}setApprovalError("");const actor=$("#approval-actor").value.trim();const reason=$("#approval-reason").value.trim()||"审批驳回";try{const payload=await api(`/api/incidents/${state.current.id}/reject`,{method:"POST",body:JSON.stringify({actor,reason})});state.current=payload.incident;state.resumeAfterApproval=false;$("#approval-dialog").close();announce("执行计划已驳回，未发生写操作。");await refreshAll()}catch(error){reportError(error,true)}}
function setApprovalError(message,invalidActor=Boolean(message)){const error=$("#approval-error");const actor=$("#approval-actor");error.textContent=message;error.hidden=!message;actor.setAttribute("aria-invalid",String(Boolean(message)&&invalidActor))}
function reportError(error,inDialog=false){const message=error?.message||"未知错误";setRunState(`ERROR / ${message}`);announce(`操作失败：${message}`);if(inDialog){const invalidActor=error?.code==="invalid_input";setApprovalError(message,invalidActor);if(invalidActor)$("#approval-actor").focus()}}
function setRunState(message){$("#run-state").textContent=message}
function shortHash(value,length=12){if(!value)return"—";return value.length>length?`${value.slice(0,length)}…`:value}
function formatTime(value){const date=new Date(value);return Number.isNaN(date.getTime())?"--:--:--":date.toLocaleTimeString("zh-CN",{hour12:false})}
function delay(milliseconds){return new Promise(resolve=>window.setTimeout(resolve,milliseconds))}
window.addEventListener("DOMContentLoaded",bootstrap);
